--- # cluster configuration

- hosts: master_nodes
  become: yes
  remote_user: ec2-user
  tasks:
    - name: kubeadm init with pod network cidr confiuration
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16
      args:
        executable: /bin/bash
      register: kubeadm_output

    - name: admin.conf $HOME/.kube/config
      become: no
      become_method: sudo
      shell:  "{{ lookup('file', 'script/kubernetes_admin_conf') }}"
      args:
        executable: /bin/bash

- hosts: worker_nodes
  become: yes
  remote_user: ec2-user
  tasks:
    - name: join to the cluster
      shell: $(cat "{{ kubeadm_output }}" | grep  -A 2 "kubeadm join")
      args:
        executable: /bin/bash