--- # cluster configuration

- hosts: master_nodes
  become: yes
  remote_user: ec2-user
  tasks:
    - name: kubeadm init with pod network cidr confiuration
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16
      args:
        executable: /bin/bash
      register: kubeadm_init_output

    - name: admin.conf $HOME/.kube/config
      become: no
      become_method: sudo
      shell:  "{{ lookup('file', 'script/kubernetes_admin_conf') }}"
      args:
        executable: /bin/bash

    - name: echo
      debug:
        msg: "{{ kubeadm_init_output['stdout'] }}"

    - name: prepare kubeadm join command
      shell: echo "{{ kubeadm_init_output['stdout']  }}" | grep -A 2 "kubeadm join"
      args:
        executable: /bin/bash
      register: kubeadm_join_command

    - name: echo
      debug:
        msg: "{{ kubeadm_join_command['stdout_lines'][0] }}"

- hosts: worker_nodes
  become: yes
  remote_user: ec2-user
  tasks:
    - name: join to the cluster
      shell: "sudo {{ hostvars[groups['master_nodes'][0]]['kubeadm_join_command']['stdout_lines'][0] }}"
      args:
        executable: /bin/bash