--- # cluster configuration

- hosts: master_nodes
  become: yes
  remote_user: ec2-user
  tasks:
    - name: set kubernetes repository
      shell:  "{{ lookup('file', 'script/Kubernetes_in_same_group') }}"
      args:
        executable: /bin/bash

    - name: restart service kubelet,and also issue daemon-reload to pick up config changes
      systemd:
        state: restarted
        daemon_reload: yes
        name: kubelet

    - name: kubeadm init with pod network cidr confiuration
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16
      args:
        executable: /bin/bash
      register: kubeadm_output

    - name: set kubernetes repository
      shell:  "{{ lookup('file', 'script/kubernetes_admin_conf') }}"
      args:
        executable: /bin/bash

- hosts: worker_nodes
  become: yes
  remote_user: ec2-user
  tasks:
    - name: join to the cluster
      shell:  "{{ kubeadm_output }}" # WIB I should parse the output and find the right command
      args:
        executable: /bin/bash

    - name: install Flannel
      shell:  kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      args:
        executable: /bin/bash

    - name: install Nginix Ingress Controller
      shell:
      args:
        executable: /bin/bash