- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  tasks:
    - name: get subnet info
      ec2_vpc_subnet_info:
        subnet_ids: "{{ aws.vpc.subnet_id }}"
      register: subnetInfo

    - name: debug
      debug:
        msg: "{{ subnetInfo }}"

    - name: ssh sg
      ec2_group:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: "{{ aws_region }}"

        name: ssh-sg
        description: master sg
        vpc_id: "{{ aws.vpc.id }}"
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
      register: sshSecurityGroup

    - name: master sg
      ec2_group:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: "{{ aws_region }}"

        name: master-sg
        description: master sg
        vpc_id: "{{ aws.vpc.id }}"
        rules:
          - proto: tcp
            ports:
              - 6443
              - 2379 - 2380
              - 10251
              - 10255
              - 10250
              - 10252
            cidr_ip: "{{ subnetInfo.subnets[0]['cidr_block'] }}"
      register: masterSecurityGroup

    - name: worker sg
      ec2_group:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: "{{ aws_region }}"

        name: worker-sg
        description: master sg
        vpc_id: "{{ aws.vpc.id }}"
        rules:
          - proto: tcp
            ports:
              - 10250
              - 10255
              - 30000-32767
            cidr_ip: "{{ subnetInfo.subnets[0]['cidr_block'] }}"
          - proto: udp
              ports:
                - 8285
                - 8472
              cidr_ip: "{{ subnetInfo.subnets[0]['cidr_block'] }}"
      register: workerSecurityGroup

    - name: web sg
      ec2_group:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: "{{ aws_region }}"

        name: balancer-sg
        description: balancer sg
        vpc_id: "{{ aws.vpc.id }}"
        rules:
          - proto: tcp
            ports:
              - 80
            cidr_ip: 0.0.0.0/0
      register: balancerSecurityGroup

    - name: Master Provision Instances
      ec2:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        ec2_region: "{{ aws_region }}"

        zone: "{{ aws.ec2.zone }}"
        instance_type: "{{ aws.ec2.instance_type }}"
        image: "{{ aws.ec2.ami }}"
        keypair: "{{ aws.ec2.keypair }}"
        assign_public_ip: yes
        vpc_subnet_id: "{{ aws.vpc.subnet_id }}"
        group_id:
          - "{{ sshSecurityGroup['group_id'] }}"
          - "{{ masterSecurityGroup['group_id'] }}"
          - "{{ balancerSecurityGroup['group_id'] }}"
        exact_count:  "{{ aws.ec2.master.instances }}"
        wait: true
        count_tag:
          Name: "{{ aws.ec2.master.name }}"
        instance_tags:
          Name: "{{ aws.ec2.master.name }}"

    - name: Workers Provision Instances
      ec2:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        ec2_region: "{{ aws_region }}"

        zone: "{{ aws.ec2.zone }}"
        instance_type: "{{ aws.ec2.instance_type }}"
        image: "{{ aws.ec2.ami }}"
        keypair: "{{ aws.ec2.keypair }}"
        assign_public_ip: yes
        vpc_subnet_id: "{{ aws.vpc.subnet_id }}"
        group_id:
          - "{{ sshSecurityGroup['group_id'] }}"
          - "{{ workerSecurityGroup['group_id'] }}"
          - "{{ balancerSecurityGroup['group_id'] }}"
        exact_count:  "{{ aws.ec2.worker.instances }}"
        wait: true
        count_tag:
          Name: "{{ aws.ec2.worker.name }}"
        instance_tags:
          Name: "{{ aws.ec2.worker.name }}"