- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  tasks:
    - name: Master Provision Instances
      ec2:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        ec2_region: "{{ aws_region }}"

        zone: "{{ aws.ec2.zone }}"
        instance_type: "{{ aws.ec2.instance_type }}"
        image: "{{ aws.ec2.ami }}"
        keypair: "{{ aws.ec2.keypair }}"
        assign_public_ip: yes
        vpc_subnet_id: "{{ aws.vpc.subnet_id }}"
        group_id:
          - "{{ aws.security_group.k8s.master }}"
          - "{{ aws.security_group.web }}"
        exact_count:  "{{ aws.ec2.master.instances }}"
        wait: true
        count_tag:
          Name: "{{ aws.ec2.master.name }}"
        instance_tags:
          Name: "{{ aws.ec2.master.name }}"

    - name: Workers Provision Instances
      ec2:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        ec2_region: "{{ aws_region }}"

        zone: "{{ aws.ec2.zone }}"
        instance_type: "{{ aws.ec2.instance_type }}"
        image: "{{ aws.ec2.ami }}"
        keypair: "{{ aws.ec2.keypair }}"
        assign_public_ip: yes
        vpc_subnet_id: "{{ aws.vpc.subnet_id }}"
        group_id:
          - "{{ aws.security_group.k8s.worker }}"
          - "{{ aws.security_group.web }}"
        exact_count:  "{{ aws.ec2.worker.instances }}"
        wait: true
        count_tag:
          Name: "{{ aws.ec2.worker.name }}"
        instance_tags:
          Name: "{{ aws.ec2.worker.name }}"