--- # install CoreOS Flannel and nginix ingress controller

- hosts: master_nodes
  remote_user: ec2-user
  tasks:
    - name: install Flannel
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      args:
        executable: /bin/bash

    - name: install Nginix Ingress Controller Mandatory
      shell: kubectl apply -f  "{{ lookup('file', 'script/ingress_mandatory.yml') }}"
      args:
        executable: /bin/bash

    - name: install Nginix Ingress Controller deployment
      shell: kubectl apply -f  "{{ lookup('file', 'script/ingress_controller.yml') }}"
      args:
        executable: /bin/bash