--- # install CoreOS Flannel and ngnix ingress controller

- hosts: master
  remote_user: ec2-user
  tasks:
    - name: install Flannel
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      args:
        executable: /bin/bash

    - name: install Nginix Ingress Controller Mandatory
      shell:  kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.30.0/deploy/static/mandatory.yaml
      args:
        executable: /bin/bash

    - name: install Nginix Ingress Controller deployment
      shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.30.0/deploy/static/provider/baremetal/service-nodeport.yaml
      args:
        executable: /bin/bash

    - name: ingress node port
      shell: |-
        kubectl get svc -n ingress-nginx | grep NodePort | awk '{ print $5 }' | awk -F , ' { print $1 } ' | awk -F : ' { print $2 } ' | awk -F / ' { print $1 } '
      args:
        executable: /bin/bash
      register: kube_ingress_nodeport

    - name: logs
      debug:
        msg: "ingress service nodeport: {{ kube_ingress_nodeport }}"