# add ec2 instance in inventory

- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  tasks:
    - name: EC2 Master facts
      ec2_instance_info:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        ec2_region: "{{ aws_region }}"
        filters:
          tag:Name: "{{ aws.ec2.master.name }}"
      register: masterNodesEc2

    - name: master nodes inventory
      add_host:
        hostname: '{{ item.public_ip_address }}'
        private_ipv4: '{{ item.private_ip_address }}'
        groupname: master
        ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file }}"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      loop: '{{ masterNodesEc2.instances }}'

    - name: EC2 Worker facts
      ec2_instance_info:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        ec2_region: "{{ aws_region }}"
        filters:
          tag:Name: "{{ aws.ec2.worker.name }}"
      register: workerNodesEc2

    - name: make worker nodes inventory
      add_host:
        hostname: '{{ item.public_ip_address }}'
        private_ipv4: '{{ item.private_ip_address }}'
        groupname: worker
        ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file }}"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      loop: '{{ workerNodesEc2.instances }}'