--- # play book for build a new onlyone-portal platform server

# provisioning of EC2 Instances
- name: server provisioning
  import_playbook: ec2-provisioner.yml

# make inventory
- name: server provisioning
  import_playbook: make_inventory.yml

# setup platform instances
- name: Configure EC2 Instances
  import_playbook: cluster_setup.yml

# setup platform instances
- name: Configure EC2 Instances
  import_playbook: cluster_init.yml

# setup platform instances
- name: Configure EC2 Instances
  import_playbook: ingress_controller_setup.yml