--- # Kubernetes installation with KubeAdm

- name: server provisioning
  import_playbook: provisioner.yml

- name: make dynamic inventory
  import_playbook: make_inventory.yml

- name: cluster setup
  import_playbook: cluster_setup.yml

- name: cluster init
  import_playbook: cluster_init.yml

- name: cluster init
  import_playbook: ingress_controller_setup.yml

- hosts: master_nodes
  remote_user: ec2-user
  tasks:
    - name: install sample application
      shell:  kubectl apply -f https://raw.githubusercontent.com/mrFlick72/ansible-playground/master/kubernetes-sample/legacy-webapp.yml
      args:
        executable: /bin/bash