--- # Kubernetes installation with KubeAdm

- name: server provisioning
  import_playbook: provisioner.yml

- name: server provisioning
  import_playbook: make_inventory.yml

- name: cluster setup
  import_playbook: cluster_setup.yml

- name: cluster init
  import_playbook: cluster_init.yml

- name: cluster init
  import_playbook: ingress_controller_setup.yml