apiVersion: apps/v1
kind: Deployment
metadata:
  name: very-legacy-webapp
  labels:
    app: very-legacy-webapp
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: very-legacy-webapp
  template:
    metadata:
      labels:
        app: very-legacy-webapp
    spec:
      containers:
        - name: very-legacy-webapp
          image: mrflick72/very-legacy-webapp:latest
          ports:
            - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: very-legacy-webapp
spec:
  selector:
    app: very-legacy-webapp
  ports:
    - protocol: TCP
      port: 8080
---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: very-legacy-webapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /very-legacy-webapp/?(.*)
            backend:
              serviceName: very-legacy-webapp
              servicePort: 8080