--- # AWS provisioning

- hosts: localhost
  gather_facts: no
  vars_files:
    - balancer_keys.yml
  tasks:
    - name: load balancer provisioning
      import_tasks: provisioner.yml
- hosts: localhost
  gather_facts: no
  vars_files:
    - webservers_keys.yml
  tasks:
    - name: web server worker provisioning
      import_tasks: provisioner.yml
