- hosts: localhost
  gather_facts: yes
  vars_files:
    - keys.yml
  tasks:
    - name: Get EC2 Instances facts
      ec2_instance_facts:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"  
        ec2_region: "{{ AWS_REGION }}"
        filters: 
          tag:Name: "{{ AWS_EC2_TAG_NAME }}"
      register: ec2_facts
    - name: Terminate instances
      ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"  
        ec2_region: "{{ AWS_REGION }}"
        state: absent
        instance_id:
          - "{{ item.instance_id }}"
      loop: "{{ ec2_facts.instances }}"
      register: ec2
    - debug:
        var: ec2
