# add ec2 instance in inventory

- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  tasks:
    - name: Get Load Balancer EC2 Instances facts
      ec2_instance_facts:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        filters:
          tag:Name: "balancer"
      register: loadBalancerEc2

    - name: Get Web Server EC2 Instances facts
      ec2_instance_facts:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        filters:
          tag:Name: "web-server"
      register: webServerEc2


    - name: add Load Balancer EC2 host to inventory
      add_host:
        hostname: '{{ item.public_ip_address }}'
        groupname: loadbalancer
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      loop: '{{ loadBalancerEc2.instances }}'

    - name: add Web Server EC2 host to inventory
      add_host:
        hostname: '{{ item.public_ip_address }}'
        groupname: content_server
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      loop: '{{ webServerEc2.instances }}'

- hosts:
    - loadbalancer
    - content_server
  become: yes
  gather_facts: no
  remote_user: ec2-user
  tasks:
    - name: Wait for SSH to come up
      wait_for_connection:
        delay: 20
        timeout: 180