---
- name: server provisioning
  import_playbook: provisioner.yml

- name: make inventory
  import_playbook: inventory.yml

- name: make httpd-load-balancer
  import_playbook: ../../httpd-load-balancer/play-book.yml